# -*- coding: utf-8 -*-
"""sentence similarity project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hDDdObZ-rFsge-9D-ok8F0dmMTfFhnf
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#Load the model
model=SentenceTransformer('all-MiniLM-L6-V2')

#Take input from user
text1=input("Enter text 1:")
text2=input("Enter text 2:")

#Convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)

#Calculate similarity
similarity = util.cos_sim(embedding1,embedding2)

#show result
print("\n Similarity Score:",round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level:High")
elif similarity > 0.4:
  print("Similarity Level:Medium")
else:
  print("Similarity Level:Low")