# -*- coding: utf-8 -*-
"""Text Generationcode.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_Ac4S2POVu0aU_aJV-Lxi5W8j0FRll-
"""

!pip install transformers torch

from transformers import pipeline

#Load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

#input prompt
prompt = "Artificial Intelligence in finance will"

#Generate text
result = generator(prompt,max_length = 50,num_return_sequences = 1)
print("AI Generated Text:")
print(result[0]['generated_text'])